name: ipe
version: 7.2.5
summary: Ipe http://ipe.otfried.org/
description: Drawing editor for creating figures in PDF or PS formats
  Ipe supports making small figures for inclusion into LaTeX
  documents as well as making multi-page PDF presentations
  Ipe's main features are
    * Entry of text as LaTeX source code. This makes it easy to enter
      mathematical expressions, and to reuse the LaTeX-macros of the main
      document.  In the display text is displayed as it will appear in
      the figure.
    * Produces pure Postscript/PDF, including the text. Ipe converts the
      LaTeX-source to PDF or Postscript when the file is saved.
    * It is easy to align objects with respect to each other (for
      instance, to place a point on the intersection of two lines, or to
      draw a circle through three given points) using various snapping
      modes.
    * Users can provide ipelets (Ipe plug-ins) to add functionality to
      Ipe.  This way, Ipe can be extended for each task at hand.
    * The text model is based on Unicode, and has been tested with Korean,
      Chinese, and Japanese.

confinement: devmode  # use "strict" to enforce system access only via declared interfaces

parts:
  ipe:
    source: https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.5-src.tar.gz
    source-type: tar
    source-subdir: src
    plugin: make
    make-parameters:
      - IPEPREFIX=../../../install
      - QT_SELECT=5
    build-packages:
      - libcairo2-dev
      - libfreetype6-dev
      - liblua5.2-dev
      - libjpeg8-dev
      - libpng12-dev
      - make
      - qtbase5-dev
      - qtbase5-dev-tools
      - zlib1g-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A part in the cloud


apps:
  ipe:
    command: bin/ipe
    plugs:
      - x11

  ipetoipe:
    command: bin/ipetoipe

  ipeextract:
    command: bin/ipeextract

  iperender:
    command: bin/iperender

  ipescript:
    command: bin/ipescript

  ipe6upgrade:
    command: bin/ipe6upgrade
